heat_template_version: 2013-05-23

description: >
  Dumb provider resource bar

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance

  instance_type:
    type: string
    description: Instance type
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium, m1.large]
        description: instance_type must be one of m1.small, m1.medium or m1.large

  image_id:
    type: string
    description: ID of the image to use
    default: 3e6270da-fbf7-4aef-bc78-6d0cfc3ad11b


resources:
  bar_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data: |
        #!/bin/bash -v
        echo "Bar" > /jdob-id


outputs:
  bar_ip:
    description: IP of the created bar instance
    value: { get_attr: [bar_instance, first_address] }
